name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for running containers
        run: |
          echo "Checking for running containers..."
          docker ps -q | xargs -r docker stop  # Остановить все запущенные контейнеры

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose -f docker-compose.yml exec backend ./mvnw test -q  # Запуск тестов для Spring приложения
          docker-compose -f docker-compose.yml down  # Остановка и удаление контейнеров
